<?php
define('FA_SRC_DIR', __DIR__ . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR);

define('FA_DEST_DIR', __DIR__ . DIRECTORY_SEPARATOR . 'core' . DIRECTORY_SEPARATOR . 'Field' . DIRECTORY_SEPARATOR);
?>